### ISSUE TITLE
Not able to create diretcory

### ISSUE THREAD

**Issue by anamika06jain** [AFAgarap/cnn-svm#26]
Hello i have tried to run your code but it is not able to create log directory. i have created manually and pass path of that but then also it is showing the same error.
"tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: C:/Users/Anamika/Downloads/cnn-svm-master/cnn-svm-master/logsThu Aug  9 18:32:45 2018-training; Invalid argument"

**Comment by arianyambao** [comment]
hi @anamika06jain , I think you're using a Windows OS and unlike Unix based systems, directories containing characters such as `:` cannot be saved. As a workaround Try looking for the saving function and change the part where `:` is being written.

**Comment by kimia80** [comment]
How we can run in Jupyter ?

**Comment by AFAgarap** [comment]
You can't. You have to get the code from the source, i.e. `main.py`
