### ISSUE TITLE
【Question】 How to import my own (training, testing) pictures

### ISSUE THREAD

**Issue by xdwgood** [AFAgarap/cnn-svm#31]
Thanks for this meaningful open source project！
Now that we use the MNIST dataset, I want to know how can I manipulate some pictures for model training?

For example, I have many pictures of "dogs", how do I use cnn-svm, thank you

**Comment by AFAgarap** [comment]
Thank you.

You can use `PIL.Image.open()` function (install by `pip3 install pillow`) to load your own images, then store them to a list or a NumPy array.

**Comment by xdwgood** [comment]
@AFAgarap  thank you!

How do I see the recognition result, is there a more intuitive display? Thank you

**Comment by AFAgarap** [comment]
It prints the accuracy and loss during training. But you can write it to use `tqdm`.

**Comment by xdwgood** [comment]
@AFAgarap  thanks

**Comment by vaerdu** [comment]
> @AFAgarap thanks

请问您用cnn_svm的代码成功的训练了自己的数据集吗？我也想训练自己的数据集，想向您请教一下

**Comment by vaerdu** [comment]
> It prints the accuracy and loss during training. But you can write it to use `tqdm`.

  Can you provide code to train my own dataset? For example: I have a cat and dog dataset and they are all three-channel images, how do I load them into the model? Thank you so much.
