### ISSUE TITLE
Can't run the training on the model for CNNSVM

### ISSUE THREAD

**Issue by alexisfranche** [AFAgarap/cnn-svm#47]
Hi, I am trying to run the code however I am getting this error.

InvalidArgumentError: You must feed a value for placeholder tensor 'input_4/x_input' with dtype float and shape [?,784]
	 [[{{node input_4/x_input}}]]

**Comment by alexisfranche** [comment]
Any idea as to why this error is occuring?

**Comment by AFAgarap** [comment]
Inspect the shape of your tensor.

**Comment by alexisfranche** [comment]
I did and it is fine. I mean I am running your code exactly the way presented on GitHub as well as the same command line options as in the ReadMe.
________________________________

**Comment by AFAgarap** [comment]
Did you install the tf version listed in `requirements.txt`?

**Comment by alexisfranche** [comment]
Yes I have.


________________________________

**Comment by AFAgarap** [comment]
Can't help you anymore. Sorry. I've fully migrated to PyTorch. You can do some inspection of your own, check the tensor shapes.
